apiVersion: v1
kind: Service
metadata:
  name: energy-monitor-longterm-prometheus
  namespace: energy-monitor
  labels:
    app: energy-monitor-longterm-prometheus
spec:
  type: ClusterIP
  selector:
    app: energy-monitor-longterm-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
