# Auto-generated by tools_gif_to_py.py from assets/checkmark.gif
WIDTH = 46
HEIGHT = 46
ROW_BYTES = 6
FRAME_COUNT = 30
DURATIONS = [30, 40, 30, 30, 40, 30, 30, 40, 30, 30, 40, 30, 30, 40, 60, 40, 30, 30, 40, 30, 30, 40, 30, 30, 40, 30, 30, 40, 30, 30]
DATA_FILE = 'checkmark_anim.bin'
