"""Converts an animated GIF into a packed 1-bit frame sequence for MicroPython.

Crops to the bounding box of the final frame's drawn content (GIF export
canvases usually carry padding we don't want to waste on a 128x64 display),
scales to fit the target height preserving aspect ratio, and thresholds each
frame's alpha channel to a 1-bit bitmap (MSB-first, row-major, one byte per
8 pixels per row) -- the same packing convention as qr_wifi.py/qr_url.py.

The packed frame data is written to a separate .bin file rather than embedded
as a Python bytes literal: compiling a large literal from source needs far
more scratch RAM on the ESP8266 than the final object, and raising a
MemoryError on import. Reading it as a binary file at runtime avoids that,
and lets playback pull in one frame at a time instead of holding all of them.

Usage:
    python3 tools_gif_to_py.py <input.gif> <target_height_px> <output_basename>

Writes <output_basename>.py (metadata) and <output_basename>.bin (frame data).
"""
import os
import sys

from PIL import Image, ImageSequence

ALPHA_THRESHOLD = 100


def load_frames_and_durations(path):
    im = Image.open(path)
    frames = []
    durations = []
    for frame in ImageSequence.Iterator(im):
        frames.append(frame.convert("RGBA"))
        durations.append(frame.info.get("duration", 30))
    return frames, durations


def pack_alpha(frame):
    alpha = frame.split()[-1]
    width, height = alpha.size
    row_bytes = (width + 7) // 8
    out = bytearray(row_bytes * height)
    px = alpha.load()
    for y in range(height):
        for x in range(width):
            if px[x, y] >= ALPHA_THRESHOLD:
                out[y * row_bytes + x // 8] |= 0x80 >> (x % 8)
    return bytes(out)


def convert(src_path, target_height, out_basename):
    frames, durations = load_frames_and_durations(src_path)

    last_alpha = frames[-1].split()[-1]
    bbox = last_alpha.getbbox()
    cropped = [f.crop(bbox) for f in frames]

    w, h = cropped[0].size
    scale = target_height / h
    target_width = round(w * scale)
    resized = [f.resize((target_width, target_height), Image.LANCZOS) for f in cropped]

    packed_frames = [pack_alpha(f) for f in resized]
    row_bytes = (target_width + 7) // 8
    data = b"".join(packed_frames)

    out_py = out_basename + ".py"
    out_bin = out_basename + ".bin"

    with open(out_bin, "wb") as f:
        f.write(data)

    with open(out_py, "w") as out:
        out.write("# Auto-generated by tools_gif_to_py.py from {}\n".format(src_path))
        out.write("WIDTH = {}\n".format(target_width))
        out.write("HEIGHT = {}\n".format(target_height))
        out.write("ROW_BYTES = {}\n".format(row_bytes))
        out.write("FRAME_COUNT = {}\n".format(len(packed_frames)))
        out.write("DURATIONS = {!r}\n".format(durations))
        out.write("DATA_FILE = {!r}\n".format(os.path.basename(out_bin)))

    print(
        "{}x{}, {} frames, {} bytes total -> {}, {}".format(
            target_width, target_height, len(packed_frames), len(data), out_py, out_bin
        )
    )


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("usage: tools_gif_to_py.py <input.gif> <target_height_px> <output_basename>")
        sys.exit(1)
    convert(sys.argv[1], int(sys.argv[2]), sys.argv[3])
